### PR TITLE
Implemented: TA editing

### PR DESCRIPTION
**Pull request by Gazing**
New functionality to edit TA information: name, token, and avatar.

Click on the a TA in the list to see/edit its details.

### CODE REVIEW

**Comment by hughdani** [comment]
- Currently it looks like its required that I do `npm install` while in `/ice-MC2/AdminView`. Is it possible to merge the package.json dependencies (and maybe all of `AdminView` ) to the main project? This is so running  `npm install` while in `/ice-MC2` will manage those dependencies as well.

- How can an instructor identify a message from a specific TA? With the chat history I am able to track that they are a TA and their username but not their registered name corresponding to the secret.

**Comment by Gazing** [comment]
Fixed:
- TA not clearing after logout
- Profile now updates properly but still requires a refresh for the new one to show up
- TA's login will no longer take a name as input instead name will now be automatically set to the defined TA name in AdminView

**Comment by hughdani** [comment]
- image issue seems to be fixed

- (bug) although if you select log in as TA, the username field for the form must still be filled with the name of the TA or else they cannot login with just the secret. As a result, I cannot check if the other issues have been fixed.

**Comment by hughdani** [comment]
- (UX) the messages from TA's always appear on the left side even if its their own message, refreshing fixes this
- all other issues noted above (aside from dependencies which we will ignore for now) have been resolved

**Comment by Gazing** [comment]
TA message appearing on the wrong side has been fixed.

**Pull request merged**
