### PR TITLE
Fully working image browser

### PR DESCRIPTION
**Pull request by junthehacker**
SVG browser is now fully functional.
* New RESTful API endpoints `/api/v1` and `/api/v1/image-libraries`
* New `config/config.js` file, we should start using config files IMMEDIATELY, stop hard coding stuff.
* For all elements in ice.html, now if you have a class `ignore-touch-conversion`, then all touch event will not convert to mouse event, this is helpful if your plugin handles touch differently.
* `/imglib-maker` for easy image library editing.

### Config
This will allow us to load a certain image libraries automatically.
```
module.exports = {
    version: 'v1.0',
    accreditedImageLibraries: [
        {
            'name': 'Default Library',
            'auto-load': true,
            'link': '/docs/img-libs/MC^2+Default+Image+Library+by+Jun+Zheng.json'
        }
    ]
}

```

image uploaded from ios

### CODE REVIEW

**Comment by junthehacker** [comment]
Lol, totally forgot to fix that.

Currently you must host it somewhere.

Sent from my iPhone

On Mar 15, 2018, at 3:47 PM, Daniel Hugh <notifications@github.com<mailto:notifications@github.com>> wrote:


@hughdani requested changes on this pull request.

  *   (UX) I get this when I click Cancel right after after clicking Import Library File.

[image]<https://user-images.githubusercontent.com/31714259/37486607-6053dc0c-2865-11e8-8966-41843490c5c0.png>

  *   What does a user require to import the file they made? Since the export option downloads a json file (and we don't store their library on the server), can they import this file directly from their file system, or does it need to be hosted somewhere?

**Comment by junthehacker** [comment]
@hughdani 
Fixed

**Comment by hughdani** [comment]
@junthehacker Sorry I was ambiguous the first time as I did not realize there were two buttons to import. I was referring to the Import Library File button in `/imglib-maker`. This issue is still occurring. I did not check this issue in the actual class room previously, however as of now it is not an issue there.

**Comment by junthehacker** [comment]
@hughdani 
Fixed as well.

**Pull request merged**
