### PR TITLE
Add loading indicator when sending images from chatroom

### PR DESCRIPTION
**Pull request by junthehacker**
add loading indicator when sending images from chatroom

basically a blue bar on top of text box.

removed iOS orientation fix because it will break everything.

### CODE REVIEW

**Comment by hughdani** [comment]
- Can't seem to get the loading bar to show. Could you upload a screenshot of it? 

- (bug?) I tried to upload larger files to simulate longer loading to test the loading bar however I am unable to upload an image greater than 3.7KB. I do not get the expected alert either. From the alert message in the code it looks like the limit is 25MB?

- (cleanup) Since the iOS orientation was removed, you should clean up the dependencies in package.json and babelrc. As a side note, I think changing the .babelrc file only effects files that you manually transpile. There is a variable containing local config settings for babel in gulp.js that handles  bundles.

**Comment by junthehacker** [comment]
Yea, it will be very hard to see if you upload small images.
Unfortunately i am unable to reproduce the bug, i can upload extremely large images from my phone.

I will clean-up the code.

**Comment by hughdani** [comment]
Strange, earlier pull did not give me the updated version. Works fine now.

**Comment by junthehacker** [comment]
@hughdani 
actually after `git rebase origin/master` and recompiling all js code, everything works.
so no more cleanup, this should be able to be merged.

**Pull request merged**
